---
deployment:
  tasks:
    - export DEPLOYPATH=/home/siaset2/public_html/
    - /bin/cp -Rf app $DEPLOYPATH
    - /bin/cp -Rf public $DEPLOYPATH
    - /bin/cp -Rf system $DEPLOYPATH
    - /bin/cp -Rf writable $DEPLOYPATH
    - /bin/cp -f spark $DEPLOYPATH
    - /bin/cp -f .env.production $DEPLOYPATH/.env
    - /bin/cp -f root.htaccess $DEPLOYPATH/.htaccess
    - /bin/chmod -R 755 $DEPLOYPATH/writable
